### ISSUE TITLE
Needs Title

### ISSUE THREAD

**Issue by jamemcc** [nmeliasp/Data-Viz#1]
Needs a general title to start you thinking about what the data is.  On first starting it I can see height on one axis and HR on the other.  I'm suspecting that HR may be Home Runs - so baseball but took me a little to get that far.  I'm assuming now it's probably the # of homeruns for players based on their height, so possibly "Understanding how Major League Players height is related to the # of Home Runds they've Hit"

**Comment by nmeliasp** [comment]
Chart Title added. Height vs Home Runs
