### ISSUE TITLE
What is the population

### ISSUE THREAD

**Issue by jamemcc** [nmeliasp/Data-Viz#3]
Because there is a lot of overlapping in the dots it leads me to wonder how big the population is (maybe 100 players or is it 1000s and in fact then what is the basis for the selection - is it all Major Leaguers or a subset or more than that league and for what timeframe.

**Comment by nmeliasp** [comment]
The data appears to be a subset of Major Leaguers and doesn't include any times data. There are 1157 players. I tried to style the circles and make them more opaque.
